#pragma once

// glfw3.h
#define WGINE_MOUSE_BUTTON_1         0
#define WGINE_MOUSE_BUTTON_2         1
#define WGINE_MOUSE_BUTTON_3         2
#define WGINE_MOUSE_BUTTON_4         3
#define WGINE_MOUSE_BUTTON_5         4
#define WGINE_MOUSE_BUTTON_6         5
#define WGINE_MOUSE_BUTTON_7         6
#define WGINE_MOUSE_BUTTON_8         7
#define WGINE_MOUSE_BUTTON_LAST      WGINE_MOUSE_BUTTON_8
#define WGINE_MOUSE_BUTTON_LEFT      WGINE_MOUSE_BUTTON_1
#define WGINE_MOUSE_BUTTON_RIGHT     WGINE_MOUSE_BUTTON_2
#define WGINE_MOUSE_BUTTON_MIDDLE    WGINE_MOUSE_BUTTON_3
